
name: Workflow with artifacts


on: [push]
 
env:
  ARTIFACT_NAME: myArtifact
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - check out the code
        uses: actions/checkout@v3

      - name: step 2 - upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .

 
