name: Deploy .Net app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: test
        run: dotnet test --no-build 

      - name: Publish
        run: dotnet publish src/GitActionProject/Git-Actions-Practise.csproj --self-contained=true -c Release -o publish /p:PublishSingleFile=true
      

      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v3.1.2
        with:
          name: consoleApp
          path: ./publish
          if-no-files-found: error
  deploy:
    name: Deploy Artifact ot github runner
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "prod"
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: consoleApp 
      - name: Set to executable 
        run: |
          ls
          chmod +x Git-Actions-Practise

      - name: Run app
        run: ./Git-Actions-Practise       
