

name: CI/CD 

on: [push]

env:
  ARTIFACT_NAME: myARTIFACT

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Checkout and run
        run: csc csharp.cs
  job2:
    runs-on: windows-latest
    needs: [job1]
    steps:
      - name: build
        
        uses: actions/checkout@v3
       
      - name: artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
       
       
