name: Python Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    environment: developement
    steps:
      - uses: actions/checkout@v2
      - run: python hello.py
      
  build:
    needs: [test]
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: hello
          path: .
